name: ddlx-track3-solution
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.13
  - pip
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-cuda=11.8
  - numpy=1.26.3
  - pandas=2.2.3
  - pillow=10.2.0
  - pyyaml=6.0.2
  - scikit-learn=1.5.2
  - pip:
      - timm==0.6.11
      - ultralytics==8.4.53
      - opencv-python==4.10.0.84
      - facenet-pytorch==2.5.3
